### PR TITLE
fix AMP compatibility for Standard and Transitional mode (#181)

### LINKED ISSUE #181: Invalid markup by AMP plugin with enabled JavaScript tracking
Every time I save a post I get two validation errors in the [official AMP plugin](https://wordpress.org/plugins/amp/) with enabled JavaScript tracking:

> Invalid inline script
> Fehlercode
> DISALLOWED_TAG
> Ungültiges Markup
> <script … >
> Element-Attribute
> type	text/javascript
> id	statify-js-js-extra
> Element-Name
> script
> Übergeordnetes Element
> body
> Textinhalt
>  128 Bytes
> /* <![CDATA[ */
> var statify_ajax = {"url":"https:\/\/kittmedia.com\/wp-admin\/admin-ajax.php","nonce":"3d82495992"};
> /* ]]> */

> Invalid script snippet.min.js
> Fehlercode
> DISALLOWED_TAG
> Ungültiges Markup
> <script … >
> Element-Attribute
> type	text/javascript
> src	https://kittmedia.com/wp-content/plugins/statify/js/snippet.min.js
> id	statify-js-js
> Element-Name
> script
> Übergeordnetes Element
> body

Due to the fact that Statify is recommending using the JavaScript tracking method to track AMP pages as well, I would assume that it will work properly. However, as soon as this invalid markup gets removed (which is required in order to serve AMP pages), Statify isn’t able anymore to track any AMP page visits.

AMP version: 2.0.0 (already occurred in version 1.5.x)
Statify version: 1.8.0
WordPress version: 5.5.0

### PR DESCRIPTION
**Pull request by stklcode**
Standard and Transitional mode use the `amp_analytics_entries` hook, Reader mode uses `amp_post_template_analytics`.
We only added a filter for the latter, so AMP compatibility was only available in Reader mode.

### CODE REVIEW

**Comment by MatzeKitt** [comment]
This works for me. 👍🏻

**Comment by stklcode** [comment]
Great. Thanks for the quick feedback.

I‘ll add a condition to remove the unnecessary scripts tomorrow (if nobody is faster), then we can rollout the fix.

**Comment by stklcode** [comment]
I've added the necessary check within the `Statify_Frontend::wp_footer()` method. Along with this change we now check for `amp_is_request()` with fallback to 'is_amp_endpoint()` (deprecated in AMP plugin 2.0).

An earlier check, e.g. not register `wp_footer` hook at all in the `Statify::init()` phase is not possible this way, because the AMP check is not initialized that early, so we jump out in the very first check if the actual hook.

**Comment by MatzeKitt** [comment]
Also the check in `wp_footer()` is working for me. Thank you. 👍🏻

File: inc/class-statify-frontend.php [hunk 1]
```diff
@@ -404,7 +408,30 @@ public static function wp_footer() {
 	}
 
 	/**
-	 * Add amp-analytics.
+	 * Add amp-analytics for Standard and Transitional mode.
+	 *
+	 * @see hAMPttps://amp-wp.org/documentation/playbooks/analytics/
```
Comment (florianbrinkmann) [inline inc/class-statify-frontend.php]: Here is a little typo: `hAMPttps`

File: inc/class-statify-frontend.php [hunk 2]
```diff
@@ -420,32 +447,35 @@ public static function amp_post_template_analytics( $analytics ) {
...
+				'_ajax_nonce'      => wp_create_nonce( 'statify_track' ),
+				'statify_referrer' => '${documentReferrer}',
+				'statify_target'   => '${canonicalPath}amp/',
+			),
+			'triggers'       => array(
+				'trackPageview' => array(
+					'on'      => 'visible',
+					'request' => 'pageview',
+				),
+			),
```
Comment (florianbrinkmann) [inline inc/class-statify-frontend.php:478]: As I wrote in Slack, I have no real experience with AMP, but one thing I noticed here: is it correct that the `transport` key was skipped from this config array, or was that accidentally?

File: inc/class-statify-frontend.php (hunk 1 above)
Comment (stklcode) [reply inc/class-statify-frontend.php]: Obviously ... :man_facepalming:

File: inc/class-statify-frontend.php (hunk 2 above)
Comment (stklcode) [reply inc/class-statify-frontend.php:478]: Good catch! Removing the section was not intentional.

Transport defaults to `beacon`, `xhrpost` and `image` enabled (in hierarchical order), so most browsers will use a compatible method by default. However `image` uses a GET request while _Statify_ requires POST, so I've disabled it explicitly.
Both `beacon` and `xhrpost` perform well.

**Review by florianbrinkmann — APPROVED** [review]
Looks good to me
